title: Mon Blog
description: Un blog personnel hébergé sur GitHub Pages
author: DARDAR SAAD
baseurl: ""
url: "https://stodar.github.io"

theme: minima
markdown: kramdown

plugins:
  - jekyll-feed

minima:
  skin: classic

# Génère automatiquement /blog/mon-article/ pour chaque post
permalink: /blog/:title/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
